server:
  port: 8082

spring:
  profiles:
    active: dev

ice:
  app: 1
  server: zookeeper:localhost:2182,localhost:2181,localhost:2103
  scan: com.ice.test
  pool:
    parallelism: -1
test:
  value: 123
environment: dev